version: '3.3'

services:
  database_test:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: milleteschi
      POSTGRES_DB: testdb
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_test_volume:/var/lib/postgresql/data
      - ./database/tests:/docker-entrypoint-initdb.d:ro
    command: ['postgres', '-p', '5432']
      #- ./database/build:/docker-entrypoint-initdb.d_copy/01_build:ro
      #- ./database/tests:/docker-entrypoint-initdb.d_copy/02_tests:ro
    #command: "sh -c 'cp /docker-entrypoint-initdb.d_copy/01_build/* /docker-entrypoint-initdb.d && cp /docker-entrypoint-initdb.d_copy/02_tests/* /docker-entrypoint-initdb.d && su -c \"postgres -p 5432\" postgres'"
    networks:
      - lso_test_network

  backend_test:
    image: lso_backend:1
    command: sh -c "dockerize -wait tcp://database_test:5432 -timeout 60s make test"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: milleteschi
      POSTGRES_DB: testdb
      POSTGRES_PORT: 5432
      POSTGRES_HOST: database_test
    volumes:
      - './backend:/cfiles'
    working_dir: '/cfiles'
    depends_on:
      - database_test
    networks:
      - lso_test_network

networks:
  lso_test_network:
    driver: bridge
