version: '3.3'

services:
  database:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: milleteschi
      POSTGRES_DB: lsodct
    ports:
      - '5432:5432'
    command: ['postgres', '-p', '5432']
    volumes:
      - ./postgres_volume:/var/lib/postgresql/data
      - ./database/build_schema:/docker-entrypoint-initdb.d:ro
    networks:
      - lso_network

  backend:
    image: lso_backend:1
    command: sh -c "dockerize -wait tcp://database:5432 -timeout 120s sh build_and_run.sh release"
    environment:
      REDISHOST: 'redis'
      REDISPORT: '6379'
      SERVER: 'LSO-Backend/1.0.0'
      SERVER_PORT: 8080
      SERVER_MAX_CONNECTION: 100
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: milleteschi
      POSTGRES_DB: lsodct
      POSTGRES_PORT: 5432
      POSTGRES_HOST: database
    volumes:
      - './backend:/cfiles'
    working_dir: '/cfiles'
    depends_on:
      - database
    ports:
      - '8080:8080'
    networks:
      - lso_network

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - lso_network

networks:
  lso_network:
    driver: bridge
