
#include <hiredis/hiredis.h>
#include <stdbool.h>

extern redisContext *cache_connection;

bool insert_key_value_pair_into_cache(const char* key, const char* val);
char* get_value_by_key(const char* key);
char* generate_random_key();
char* insert_value_with_autogenerated_unique_key(const char* value);