
#include <hiredis/hiredis.h>
#include "cache.h"
#include "assert.h"
#include <stdbool.h>

#define EXPIRATION_TIME_SECONDS 180 //3 minutes

char* sha256_hash_number(long long int num);

bool insert_key_value_pair_into_cache(const char* key, const char* val){
    redisReply* reply = redisCommand(cache_connection,"SETNX %s %s", key, val);
    bool outcome = (reply != NULL && reply->type == REDIS_REPLY_INTEGER);
    outcome &= (reply->integer == 1);
    freeReplyObject(reply);
    if (outcome){
        reply = redisCommand(cache_connection,"EXPIRE %s %d", key, EXPIRATION_TIME_SECONDS);
        outcome &= (reply != NULL && reply->type == REDIS_REPLY_INTEGER);
        outcome &= (reply->integer == 1);
        freeReplyObject(reply);
    }
    return outcome;
}

char* generate_random_key(){
    redisReply* reply = redisCommand(cache_connection,"INCR keycounter");
    assert(reply != NULL);
    assert(reply->type == REDIS_REPLY_INTEGER);
    long long int keynum = reply->integer;
    freeReplyObject(reply);
    return sha256_hash_number(keynum);
}

char* insert_value_with_autogenerated_unique_key(const char* value){
    for (int i = 0; i < 50; i++){
        char* key = generate_random_key();
        if (insert_key_value_pair_into_cache(key, value)){
            return key;
        }
        free(key);
    }
    return NULL;
}